language: ruby
rvm:
  - 2.6.1

services:
  - postgresql

before_install:
  - "echo '--colour' > ~/.rspec"
  - "echo 'gem: --no-document' > ~/.gemrc"
  - gem update --system

before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c "CREATE USER \"rails-bootstrap\" WITH PASSWORD 'rails-bootstrap';" -U postgres
  - psql -c "DROP DATABASE IF EXISTS \"rails-bootstrap_test\";" -U postgres
  - psql -c "CREATE DATABASE \"rails-bootstrap_test\" ENCODING 'utf8';" -U postgres
  - bundle exec rake db:migrate

script:
  - bundle install --jobs=3 --retry=3
  - bundle exec rubocop app spec -R --format simple
  - bundle exec rspec

cache:
  bundler: true

