:concurrency: 1
:queues:
  - default
  - mailers
:schedule:
  rent_expired:
    cron: '0 9 * * * * America/Argentina/Buenos_Aires'
    class: RentExpired
    description: 'This job send email to user when rent expires today'
